schemaVersion: 2.2.0
attributes:
  controller.devfile.io/storage-type: per-workspace
metadata:
  name: nlove-quarkus-demo
components:
- name: podman
  container: 
    image: 'registry.redhat.io/devspaces/udi-rhel8@sha256:8de469cc9131a42092bd66e0f27a52bbc9b9a449235abf5b900d172a1bd3c985'
    memoryLimit: 6Gi
    mountSources: true
    volumeMounts:
    - name: m2
      path: /home/user/.m2
    env:
      - name: name
        value: quarkus-devfile
- volume:
    size: 4Gi
  name: projects
- volume:
    size: 2Gi
  name: m2
projects:
  - name: java-demo
    git:
      remotes:
        origin: 'https://github.com/NateLove/demo-java.git'
  - name: quarkus-quickstarts
    git:
      remotes:
        origin: 'https://github.com/NateLove/quarkus-quickstarts.git'
