schemaVersion: 2.2.0
metadata:
  name: java-quarkus
components:
  - name: image-build
    container:
      sourceMapping: /projects
      memoryLimit: 8Gi
      memoryRequest: 512Mi
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      image: java-quarkus-image:latest
      endpoints:
        - exposure: public
          name: quarkus-dev
          targetPort: 8080
          protocol: https
  - name: m2
    volume:
      size: 2Gi

